load_data:
  path_data: data/green_tripdata_2022-01.parquet

preprocess:
  min_duration: 1
  max_duration: 60
  preprocessed_data: data/taxi_data_preprocessed.parquet

train:
  target_column: duration

model:
  cv: 7
  estimator_name: xgb
  estimators:
    linreg:
      param_grid:
        fit_intercept: [False]
    lassoreg:
      param_grid:
        alpha: [0.1]
        random_state: [42]
    xgb:
      param_grid:
        learning_rate: [0.28]
        max_depth: [41]
        min_child_weight: [2.44]
        reg_alpha: [0.19]
        reg_lambda: [0.02]
        random_state: [42]
  model_path: reports/best_estimator.bin
  rmse_comparison_plot: reports/RMSE_comparision.png


evaluate:
  path_data: data/green_tripdata_2022-02.parquet
  metrics_file_path: reports/metrics_file.json