load_data:
  path_data: data/green_tripdata_2022-01.parquet

preprocess:
  min_duration: 1
  max_duration: 60
  preprocessed_data: data/taxi_data_preprocessed.parquet

train:
  target_column: duration

model:
  cv: 5
  estimator_name: xgb
  estimators:
    linreg:
      param_grid:
        random_state: [42]
    lassoreg:
      param_grid:
        alpha: [0.1]
        random_state: [42]
    xgb:
      param_grid:
        learning_rate: [0.28]
        max_depth: [41]
        min_child_weight: [2.44]
        reg_alpha: [0.19]
        reg_lambda: [0.02]
        random_state: [42]

evaluate:
  metrics_file_path: reports/metrics_file.json
  roc_plots_path: reports/roc.png
  precision_recall_plot_path: reports/precision_recall_curve.png