load_data:
  path_data: data/green_tripdata_2022-01.parquet

preprocess:
  min_duration: 1
  max_duration: 60
  preprocessed_data: data/taxi_data_preprocessed.parquet

train:
  target_column: duration
  test_size: 0.3
  random_state: 42
  train_pipe_path: reports/train_pipe.joblib

model: 
  criterion: gini
  max_depth: 12
  max_features: auto
  n_estimators: 5

evaluate:
  metrics_file_path: reports/metrics_file.json
  roc_plots_path: reports/roc.png
  precision_recall_plot_path: reports/precision_recall_curve.png